<?php include 'includes/header.php'; ?>
<div class="blog-post">
            <h2 class="blog-post-title">International PHP Conference 2014</h2>
            <p class="blog-post-meta">January 1, 2014 by <a href="#">Mark</a></p>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus pretium commodo felis vel ultrices. Etiam id dui eros. Praesent nunc dui, volutpat at eleifend nec, suscipit a sapien. Morbi leo urna, aliquam a purus eget, tempus cursus nisl. In hac habitasse platea dictumst. Aliquam pulvinar at lorem vel vulputate. Nunc tempus enim neque. Fusce justo nibh, volutpat eget auctor et, malesuada quis odio. Suspendisse convallis consequat lectus, ullamcorper consequat mauris luctus in. Suspendisse accumsan lorem varius tincidunt tristique. Ut nulla libero, feugiat vitae dui ac, dictum adipiscing libero. Sed sit amet augue mi. Nullam luctus ligula ultricies erat volutpat scelerisque. Etiam molestie sodales aliquam. Donec nisl odio, fringilla quis nibh quis, pulvinar ornare nibh. Integer lorem ligula, scelerisque ut felis et, pretium ultricies arcu.</p>
				<p>Phasellus dignissim sapien in nisl consequat, et scelerisque mauris pharetra. Aenean ultricies ipsum sed ornare sollicitudin. Nam tempus condimentum magna, a condimentum felis vestibulum eget. Phasellus placerat turpis nunc, in gravida tortor accumsan eget. Cras porta luctus quam, at vulputate quam dapibus sodales. Praesent sed iaculis erat. Duis ultrices neque diam, non vehicula arcu fermentum et. Duis eget vestibulum mauris, in adipiscing nisl. Curabitur mattis suscipit dictum. Donec porta in ipsum nec consequat. Phasellus ac dui a metus tristique eleifend ac et purus. Proin interdum tortor sapien, et convallis urna scelerisque eu. Quisque est est, commodo congue elit eget, scelerisque vehicula felis.
</p>
<p>
Praesent sit amet magna gravida, accumsan erat vitae, tempor libero. Mauris vel aliquet lectus, non fringilla velit. Nullam ornare congue justo, sed pharetra risus tempor ut. In et dapibus justo, sed consequat massa. Etiam sapien dui, elementum ut bibendum vitae, elementum sed erat. Etiam vel pulvinar enim, at euismod ligula. Proin laoreet, velit vitae fringilla congue, neque ante iaculis eros, at congue diam leo at lorem. Fusce eget vulputate quam. Morbi viverra felis placerat tincidunt vulputate. Praesent tincidunt eget risus eget congue. Vestibulum erat felis, pretium scelerisque urna ac, sodales pulvinar est. Integer nec metus justo. Praesent eu tristique nisi.</p>
          </div><!-- /.blog-post -->		      
<?php include 'includes/footer.php'; ?>